package com.wsy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseInterviewer<M extends BaseInterviewer<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setTel(java.lang.String tel) {
		set("tel", tel);
		return (M)this;
	}

	public java.lang.String getTel() {
		return getStr("tel");
	}

	public M setIdNum(java.lang.String idNum) {
		set("id_num", idNum);
		return (M)this;
	}

	public java.lang.String getIdNum() {
		return getStr("id_num");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setSex(java.lang.String sex) {
		set("sex", sex);
		return (M)this;
	}

	public java.lang.String getSex() {
		return getStr("sex");
	}

	public M setAge(java.lang.Integer age) {
		set("age", age);
		return (M)this;
	}

	public java.lang.Integer getAge() {
		return getInt("age");
	}

	public M setCreateBy(java.lang.Integer createBy) {
		set("create_by", createBy);
		return (M)this;
	}

	public java.lang.Integer getCreateBy() {
		return getInt("create_by");
	}

	public M setPortrait(java.lang.String portrait) {
		set("portrait", portrait);
		return (M)this;
	}

	public java.lang.String getPortrait() {
		return getStr("portrait");
	}

	public M setCourt(java.lang.String court) {
		set("court", court);
		return (M)this;
	}

	public java.lang.String getCourt() {
		return getStr("court");
	}

	public M setBuildingUnit(java.lang.String buildingUnit) {
		set("building_unit", buildingUnit);
		return (M)this;
	}

	public java.lang.String getBuildingUnit() {
		return getStr("building_unit");
	}

	public M setRoom(java.lang.String room) {
		set("room", room);
		return (M)this;
	}

	public java.lang.String getRoom() {
		return getStr("room");
	}

	public M setLatitude(java.lang.String latitude) {
		set("latitude", latitude);
		return (M)this;
	}

	public java.lang.String getLatitude() {
		return getStr("latitude");
	}

	public M setLongitude(java.lang.String longitude) {
		set("longitude", longitude);
		return (M)this;
	}

	public java.lang.String getLongitude() {
		return getStr("longitude");
	}

}
