package com.wsy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRolePermission<M extends BaseRolePermission<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
		return (M)this;
	}

	public java.lang.Integer getRoleId() {
		return getInt("role_id");
	}

	public M setPermissionId(java.lang.Integer permissionId) {
		set("permission_id", permissionId);
		return (M)this;
	}

	public java.lang.Integer getPermissionId() {
		return getInt("permission_id");
	}

	public M setCreatorId(java.lang.Integer creatorId) {
		set("creator_id", creatorId);
		return (M)this;
	}

	public java.lang.Integer getCreatorId() {
		return getInt("creator_id");
	}

	public M setUpdatorId(java.lang.Integer updatorId) {
		set("updator_id", updatorId);
		return (M)this;
	}

	public java.lang.Integer getUpdatorId() {
		return getInt("updator_id");
	}

	public M setCtime(java.util.Date ctime) {
		set("ctime", ctime);
		return (M)this;
	}

	public java.util.Date getCtime() {
		return get("ctime");
	}

	public M setUtime(java.util.Date utime) {
		set("utime", utime);
		return (M)this;
	}

	public java.util.Date getUtime() {
		return get("utime");
	}

}
