package com.wsy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseScoreFlow<M extends BaseScoreFlow<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setScore(java.lang.Double score) {
		set("score", score);
		return (M)this;
	}

	public java.lang.Double getScore() {
		return getDouble("score");
	}

	public M setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
		return (M)this;
	}

	public java.util.Date getCreatedTime() {
		return get("created_time");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setJobId(java.lang.Integer jobId) {
		set("job_id", jobId);
		return (M)this;
	}

	public java.lang.Integer getJobId() {
		return getInt("job_id");
	}

	public M setBeforeScore(java.lang.Double beforeScore) {
		set("before_score", beforeScore);
		return (M)this;
	}

	public java.lang.Double getBeforeScore() {
		return getDouble("before_score");
	}

	public M setAfterScore(java.lang.Double afterScore) {
		set("after_score", afterScore);
		return (M)this;
	}

	public java.lang.Double getAfterScore() {
		return getDouble("after_score");
	}

}
