package com.wsy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseJob<M extends BaseJob<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}

	public java.lang.String getCode() {
		return getStr("code");
	}

	public M setTaskId(java.lang.Integer taskId) {
		set("task_id", taskId);
		return (M)this;
	}

	public java.lang.Integer getTaskId() {
		return getInt("task_id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
		return (M)this;
	}

	public java.util.Date getCreatedTime() {
		return get("created_time");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setFinishTime(java.util.Date finishTime) {
		set("finish_time", finishTime);
		return (M)this;
	}

	public java.util.Date getFinishTime() {
		return get("finish_time");
	}

	public M setUpdatedBy(java.lang.Integer updatedBy) {
		set("updated_by", updatedBy);
		return (M)this;
	}

	public java.lang.Integer getUpdatedBy() {
		return getInt("updated_by");
	}

	public M setPlanAmount(java.lang.Double planAmount) {
		set("plan_amount", planAmount);
		return (M)this;
	}

	public java.lang.Double getPlanAmount() {
		return getDouble("plan_amount");
	}

	public M setFinishAmount(java.lang.Double finishAmount) {
		set("finish_amount", finishAmount);
		return (M)this;
	}

	public java.lang.Double getFinishAmount() {
		return getDouble("finish_amount");
	}

	public M setDesc(java.lang.String desc) {
		set("desc", desc);
		return (M)this;
	}

	public java.lang.String getDesc() {
		return getStr("desc");
	}

}
