package com.wsy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserName(java.lang.String userName) {
		set("user_name", userName);
		return (M)this;
	}

	public java.lang.String getUserName() {
		return getStr("user_name");
	}

	public M setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
		return (M)this;
	}

	public java.lang.String getNickName() {
		return getStr("nick_name");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setAge(java.lang.Integer age) {
		set("age", age);
		return (M)this;
	}

	public java.lang.Integer getAge() {
		return getInt("age");
	}

	public M setLastLogin(java.util.Date lastLogin) {
		set("last_login", lastLogin);
		return (M)this;
	}

	public java.util.Date getLastLogin() {
		return get("last_login");
	}

	public M setFamilyId(java.lang.Integer familyId) {
		set("family_id", familyId);
		return (M)this;
	}

	public java.lang.Integer getFamilyId() {
		return getInt("family_id");
	}

	public M setSex(java.lang.Boolean sex) {
		set("sex", sex);
		return (M)this;
	}

	public java.lang.Boolean getSex() {
		return get("sex");
	}

	public M setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
		return (M)this;
	}

	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}

	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}

	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setIsactive(java.lang.Boolean isactive) {
		set("isactive", isactive);
		return (M)this;
	}

	public java.lang.Boolean getIsactive() {
		return get("isactive");
	}

	public M setIssuper(java.lang.Boolean issuper) {
		set("issuper", issuper);
		return (M)this;
	}

	public java.lang.Boolean getIssuper() {
		return get("issuper");
	}

	public M setCreateBy(java.lang.Integer createBy) {
		set("create_by", createBy);
		return (M)this;
	}

	public java.lang.Integer getCreateBy() {
		return getInt("create_by");
	}

	public M setUpdateBy(java.lang.Integer updateBy) {
		set("update_by", updateBy);
		return (M)this;
	}

	public java.lang.Integer getUpdateBy() {
		return getInt("update_by");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setToken(java.lang.String token) {
		set("token", token);
		return (M)this;
	}

	public java.lang.String getToken() {
		return getStr("token");
	}

}
