package com.wsy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseResource<M extends BaseResource<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}

	public java.lang.String getCode() {
		return getStr("code");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setIcon(java.lang.String icon) {
		set("icon", icon);
		return (M)this;
	}

	public java.lang.String getIcon() {
		return getStr("icon");
	}

	public M setComponent(java.lang.String component) {
		set("component", component);
		return (M)this;
	}

	public java.lang.String getComponent() {
		return getStr("component");
	}

	public M setSeq(java.lang.Integer seq) {
		set("seq", seq);
		return (M)this;
	}

	public java.lang.Integer getSeq() {
		return getInt("seq");
	}

	public M setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
		return (M)this;
	}

	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setCreatorId(java.lang.Integer creatorId) {
		set("creator_id", creatorId);
		return (M)this;
	}

	public java.lang.Integer getCreatorId() {
		return getInt("creator_id");
	}

	public M setUpdatorId(java.lang.Integer updatorId) {
		set("updator_id", updatorId);
		return (M)this;
	}

	public java.lang.Integer getUpdatorId() {
		return getInt("updator_id");
	}

	public M setCtime(java.util.Date ctime) {
		set("ctime", ctime);
		return (M)this;
	}

	public java.util.Date getCtime() {
		return get("ctime");
	}

	public M setUtime(java.util.Date utime) {
		set("utime", utime);
		return (M)this;
	}

	public java.util.Date getUtime() {
		return get("utime");
	}

	public M setIsactive(java.lang.Boolean isactive) {
		set("isactive", isactive);
		return (M)this;
	}

	public java.lang.Boolean getIsactive() {
		return get("isactive");
	}

	public M setVisible(java.lang.Boolean visible) {
		set("visible", visible);
		return (M)this;
	}

	public java.lang.Boolean getVisible() {
		return get("visible");
	}

}
