package com.wsy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTask<M extends BaseTask<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setDesc(java.lang.String desc) {
		set("desc", desc);
		return (M)this;
	}

	public java.lang.String getDesc() {
		return getStr("desc");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setScore(java.lang.Integer score) {
		set("score", score);
		return (M)this;
	}

	public java.lang.Integer getScore() {
		return getInt("score");
	}

	public M setCreateBy(java.lang.Integer createBy) {
		set("create_by", createBy);
		return (M)this;
	}

	public java.lang.Integer getCreateBy() {
		return getInt("create_by");
	}

	public M setPriority(java.lang.Integer priority) {
		set("priority", priority);
		return (M)this;
	}

	public java.lang.Integer getPriority() {
		return getInt("priority");
	}

	public M setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
		return (M)this;
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public M setAlarmType(java.lang.Integer alarmType) {
		set("alarm_type", alarmType);
		return (M)this;
	}

	public java.lang.Integer getAlarmType() {
		return getInt("alarm_type");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCronExpression(java.lang.String cronExpression) {
		set("cron_expression", cronExpression);
		return (M)this;
	}

	public java.lang.String getCronExpression() {
		return getStr("cron_expression");
	}

	public M setNextFireTime(java.util.Date nextFireTime) {
		set("next_fire_time", nextFireTime);
		return (M)this;
	}

	public java.util.Date getNextFireTime() {
		return get("next_fire_time");
	}

	public M setExecutor(java.lang.Integer executor) {
		set("executor", executor);
		return (M)this;
	}

	public java.lang.Integer getExecutor() {
		return getInt("executor");
	}

}
