package com.wsy.model;

import com.wsy.model.base.BaseFamily;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Family extends BaseFamily<Family> {
	public static final Family dao = new Family().dao();
}
