package com.wsy.model;

import com.wsy.model.base.BaseJob;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Job extends BaseJob<Job> {
	public static final Job dao = new Job().dao();
}
