package com.wsy.model;

import com.wsy.model.base.BasePermissionResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PermissionResource extends BasePermissionResource<PermissionResource> {
	public static final PermissionResource dao = new PermissionResource().dao();
}
