package com.wsy.model;

import com.wsy.model.base.BaseRolePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RolePermission extends BaseRolePermission<RolePermission> {
	public static final RolePermission dao = new RolePermission().dao();
}
