package com.wsy.model;

import com.wsy.model.base.BaseScoreFlow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ScoreFlow extends BaseScoreFlow<ScoreFlow> {
	public static final ScoreFlow dao = new ScoreFlow().dao();
}
