package com.wsy.model;

import com.jfinal.plugin.activerecord.Record;
import com.wsy.model.base.BaseTask;
import com.wsy.service.TaskService;
import com.wsy.service.UserService;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Task extends BaseTask<Task> {
	public static final Task dao = new Task().dao();

	private TaskService taskService;

	public Task() {
		taskService = new TaskService();
	}

	public String getCreatorName() {
		return UserService.getUserBasic(getCreatedBy()).getNickName();
	}

	public List<Record> getExecutorList() {
		return taskService.queryExecutorsById(getId());
	}
}
