package com.wsy.model;

import com.wsy.model.base.BaseTaskUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskUser extends BaseTaskUser<TaskUser> {
	public static final TaskUser dao = new TaskUser().dao();
}
