package com.wsy.model;

import com.wsy.model.base.BaseTask;
import com.wsy.util.Constant;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Task extends BaseTask<Task> {
	public static final Task dao = new Task().dao();

	public String getCreatorName() {
		return User.dao.findById(getCreatedBy()).getNickName();
	}

	public String getExecutorName() {
		if (getType() == Constant.TaskType.PERSONAL) {
			return User.dao.findById(getExecutor()).getNickName();
		}
		return Family.dao.findById(getExecutor()).getName();
	}
}
