package com.wsy.model;

import com.jfinal.json.JFinalJson;
import com.wsy.model.base.BaseTask;
import com.wsy.service.TaskService;
import com.wsy.service.UserService;

import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Task extends BaseTask<Task> {
	public static final Task dao = new Task().dao();

	private TaskService taskService;

	public Task() {
		taskService = new TaskService();
	}

	public String getCreatorName() {
		return UserService.getUserBasic(getCreatedBy()).getNickName();
	}

	public String getExecutorList() {
		return JFinalJson.getJson().toJson(taskService.queryExecutorsById(getId()));
	}

	public Task setStartTime(long startTime) {
		set("startTime", new Date(startTime));
		return this;
	}

	public Task setEndTime(long endTime) {
		set("endTime", new Date(endTime));
		return this;
	}
}
