package com.wsy.model;

import com.wsy.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();

	public String getFamilyName() {
		return Family.dao.findById(getFamilyId()).getName();
	}
}
